function __test_1(){

S.admin=false;S.curCat=null;S.q='';S.cart=[];S.orders=[];S.editDish=null;S.editCat=null;
function rs(){const el=document.getElementById('categoryList');const a=!S.curCat;let h='<div class="cat-item'+(a?' active':'')+'" data-cat=""><span class="cat-icon">📋</span><span>全部菜品</span><span class="cat-count">'+S.dishes.length+'</span></div>';S.categories.forEach(c=>{const n=S.dishes.filter(d=>d.category===c.id).length;h+='<div class="cat-item'+(S.curCat===c.id?' active':'')+'" data-cat="'+c.id+'"><span class="cat-icon">'+(c.icon||'📄')+'</span><span>'+c.name+'</span><span class="cat-count">'+n+'</span><button class="cat-admin-edit" data-action="edit-cat">✎</button></div>'});el.innerHTML=h;el.querySelectorAll('.cat-item').forEach(it=>{it.addEventListener('click',e=>{if(e.target.closest('[data-action="edit-cat"]'))return;S.curCat=it.dataset.cat||null;S.q='';document.getElementById('searchInput').value='';ut();rs();rd();document.getElementById('leftPanel').classList.remove('open')});it.querySelector('[data-action="edit-cat"]')?.addEventListener('click',e=>{e.stopPropagation();ocm(it.dataset.cat)})});document.getElementById('leftPanel').classList.toggle('admin-mode',S.admin)}
function ut(){const h2=document.getElementById('currentCategoryTitle'),cnt=document.getElementById('resultCount'),f=flt();if(S.q.trim())h2.textContent='🔍 搜索 "'+S.q+'"';else if(S.curCat){const c=fcat(S.curCat);h2.textContent=(c?c.name+' ':'')+'菜品'}else h2.textContent='🍽️ 全部菜品';cnt.textContent='共 '+f.length+' 道菜品'}
function rd(){const el=document.getElementById('dishList'),ds=flt();if(!ds.length){el.innerHTML='<div class="dish-row-empty">暂无菜品'+(S.admin?'，点击右上角「添加菜品」开始':'')+'</div>';ut();return}el.innerHTML=ds.map(d=>{const hi=d.image&&d.image.length>100,cat=fcat(d.category),ic=hi?'<img src="'+d.image+'" alt="'+d.name+'" />':'<span class="img-placeholder">'+(d.emoji||'🍽️')+'</span>';return'<div class="dish-row'+(S.admin?' admin-mode':'')+'" data-id="'+d.id+'"><div class="dish-row-image" style="background:linear-gradient(135deg,'+(d.color||'#e74c3c')+'22,'+(d.color||'#e74c3c')+'44)">'+ic+'<div class="img-edit-overlay" data-action="upload">🖼️ 换图</div></div><div class="dish-row-info"><div class="dri-top"><div class="dri-name">'+d.name+(cat?'<span class="dri-cat-tag">'+(cat.icon||'📄')+' '+cat.name+'</span>':'')+'</div>'+(d.desc?'<div class="dri-desc">'+d.desc+'</div>':'')+'</div><div class="dri-bottom"><span class="dri-price">'+fp(d.price)+'</span><div class="dri-actions"><button class="admin-act-btn admin-act-btn-edit" data-action="edit">✏️</button><button class="admin-act-btn admin-act-btn-delete" data-action="delete">🗑️</button><button class="btn-add" data-action="add-cart">+</button></div></div></div></div>'}).join('');el.querySelectorAll('.dish-row').forEach(r=>{const id=r.dataset.id;r.querySelector('[data-action="add-cart"]')?.addEventListener('click',()=>ac(id));r.querySelector('[data-action="edit"]')?.addEventListener('click',()=>odm(id));r.querySelector('[data-action="delete"]')?.addEventListener('click',()=>dd(id));r.querySelector('[data-action="upload"]')?.addEventListener('click',()=>tiu(id))});ut()}
function ac(did){const d=fd(did);if(!d)return;const ex=S.cart.find(i=>i.dishId===did);if(ex)ex.qty+=1;else S.cart.push({dishId:did,name:d.name,price:d.price,emoji:d.emoji||'🍽️',color:d.color||'#e74c3c',image:d.image||'',qty:1});sd();rc();ub();showToast('✅ '+d.name+' 已加购','success')}
function uq(did,delta){const i=S.cart.find(x=>x.dishId===did);if(!i)return;i.qty+=delta;if(i.qty<=0){S.cart=S.cart.filter(x=>x.dishId!==did);sd();rc();ub();return}sd();rc();ub()}
function rc(){const el=document.getElementById('cartItems'),te=document.getElementById('cartTotal'),ch=document.getElementById('checkoutBtn');if(!S.cart.length){el.innerHTML='<div class="cart-empty"><span class="empty-icon">🛒</span><p>购物车是空的</p><p style="font-size:12px;margin-top:4px">快去添加喜欢的菜品吧</p></div>';te.textContent='0';ch.disabled=true;return}el.innerHTML=S.cart.map(i=>{const s=fp(i.price*i.qty),hi=i.image&&i.image.length>100;return'<div class="cart-drawer-item" data-dish="'+i.dishId+'"><div class="cdi-img">'+(hi?'<img src="'+i.image+'" />':(i.emoji||'🍽️'))+'</div><div class="cdi-info"><div class="cdi-name">'+i.name+'</div><div class="cdi-price">¥'+fp(i.price)+'</div></div><div class="cdi-qty"><button data-action="dec">−</button><span class="qty-num">'+i.qty+'</span><button data-action="inc">+</button></div><div class="cdi-total">¥'+s+'</div><button class="cdi-remove" data-action="remove">✕</button></div>'}).join('');el.querySelectorAll('.cart-drawer-item').forEach(it=>{const did=it.dataset.dish;it.querySelector('[data-action="dec"]')?.addEventListener('click',()=>uq(did,-1));it.querySelector('[data-action="inc"]')?.addEventListener('click',()=>uq(did,1));it.querySelector('[data-action="remove"]')?.addEventListener('click',()=>{S.cart=S.cart.filter(i=>i.dishId!==did);sd();rc();ub()})});te.textContent=fp(ct());ch.disabled=false}
function ub(){const b=document.getElementById('cartBadge'),c=cc();b.textContent=c>99?'99+':c;b.classList.toggle('show',c>0)}
function oc(){document.getElementById('cartOverlay').classList.add('show');document.getElementById('cartDrawer').classList.add('open');rc()}
function cc2(){document.getElementById('cartOverlay').classList.remove('show');document.getElementById('cartDrawer').classList.remove('open')}
function so(){if(!S.cart.length){showToast('购物车为空','error');return}const ri=document.getElementById('remarkInput'),r=ri.value.trim();const o={id:'ORD'+Date.now().toString(36).toUpperCase()+Math.random().toString(36).slice(2,5).toUpperCase(),items:JSON.parse(JSON.stringify(S.cart)),total:ct(),remark:r||'',time:new Date().toLocaleString('zh-CN'),status:'ok'};S.orders.unshift(o);S.cart=[];ri.value='';sd();rc();ub();cc2();showToast('订单提交成功！订单号: '+o.id,'success')}
let pui=null;function tiu(did){pui=did;const inp=document.getElementById('imageFileInput');inp.value='';inp.click()}
function odm(did){document.getElementById('dishEditTitle').textContent=did?'编辑菜品':'添加菜品';const cs=document.getElementById('editDishCategory');cs.innerHTML=S.categories.map(c=>'<option value="'+c.id+'">'+c.name+'</option>').join('');const d=did?fd(did):null;S.editDish=did||null;document.getElementById('editDishName').value=d?d.name:'';document.getElementById('editDishPrice').value=d?d.price:'';document.getElementById('editDishDesc').value=d?(d.desc||''):'';document.getElementById('editDishEmoji').value=d?(d.emoji||'🍽️'):'🍽️';document.getElementById('editDishCategory').value=d?d.category:(S.categories[0]?.id||'');const pv=document.getElementById('uploadPreview'),ui=document.getElementById('uploadIcon'),ut=document.getElementById('uploadText'),cb=document.getElementById('uploadClear');if(d&&d.image&&d.image.length>100){pv.src=d.image;pv.style.display='block';ui.style.display='none';ut.textContent='点击更换图片';cb.style.display='flex'}else{pv.style.display='none';ui.style.display='block';ut.innerHTML='点击 <strong>上传图片</strong>，支持 JPG / PNG';cb.style.display='none'}hc(d?(d.color||CS[0]):CS[0]);document.getElementById('dishEditModal').classList.add('show')}
function cdem(){document.getElementById('dishEditModal').classList.remove('show');S.editDish=null;pui=null;document.getElementById('imageFileInput').value=''}
function sde(){const n=document.getElementById('editDishName').value.trim(),p=parseFloat(document.getElementById('editDishPrice').value),cat=document.getElementById('editDishCategory').value,de=document.getElementById('editDishDesc').value.trim(),e=document.getElementById('editDishEmoji').value.trim()||'🍽️',ac2=document.querySelector('#colorOptions .active'),c=ac2?ac2.dataset.color:CS[0],pv=document.getElementById('uploadPreview'),img=(pv.style.display==='block'&&pv.src)?pv.src:'';if(!n){showToast('请输入菜品名称','error');return}if(!p||p<=0){showToast('请输入有效价格','error');return}if(!cat){showToast('请选择菜品分类','error');return}if(S.editDish){const d=fd(S.editDish);if(d){Object.assign(d,{name:n,price:p,category:cat,desc:de,emoji:e,color:c,image:img});S.cart.forEach(i=>{if(i.dishId===S.editDish)Object.assign(i,{name:n,price:p,emoji:e,color:c,image:img})});showToast('菜品已更新','success')}}else{S.dishes.push({id:gid(),name:n,price:p,category:cat,desc:de,emoji:e,color:c,image:img});showToast('菜品已添加','success')}sd();cdem();rs();rd();ub()}
function dd(did){if(!confirm('确定要删除这道菜品吗？'))return;S.dishes=S.dishes.filter(d=>d.id!==did);S.cart=S.cart.filter(i=>i.dishId!==did);sd();ra();showToast('🗑️ 菜品已删除','info')}
function ra(){rs();rd();ub()}
function ocm(cid){S.editCat=cid||null;document.getElementById('catModalTitle').textContent=cid?'编辑分类':'新增分类';const c=cid?fcat(cid):null;document.getElementById('editCatName').value=c?c.name.replace(/^[^\s]+\s*/,''):'';document.getElementById('editCatIcon').value=c?(c.icon||'📄'):'📄';document.getElementById('catDeleteBtn').style.display=cid?'flex':'none';document.getElementById('categoryModal').classList.add('show')}
function ccm(){document.getElementById('categoryModal').classList.remove('show');S.editCat=null}
function scat(){const n=document.getElementById('editCatName').value.trim(),ico=document.getElementById('editCatIcon').value.trim()||'📄';if(!n){showToast('请输入分类名称','error');return}const dn=ico+' '+n;if(S.editCat){const c=fcat(S.editCat);if(c){c.name=dn;c.icon=ico;showToast('分类已更新','success')}}else{S.categories.push({id:gid(),name:dn,icon:ico});showToast('分类已添加','success')}sd();ccm();ra()}
function dcat(){if(!S.editCat)return;const c=fcat(S.editCat);if(!c)return;const cnt=S.dishes.filter(d=>d.category===S.editCat).length;if(cnt>0&&!confirm('分类「'+c.name+'」下有 '+cnt+' 道菜品，删除分类不会删除菜品，确定继续？'))return;S.categories=S.categories.filter(x=>x.id!==S.editCat);if(S.curCat===S.editCat)S.curCat=null;sd();ccm();ra();showToast('分类已删除','info')}
function hc(c){document.querySelectorAll('#colorOptions .color-swatch').forEach(el=>el.classList.toggle('active',el.dataset.color===c))}
function ro(){const el=document.getElementById('orderList');if(!S.orders.length){el.innerHTML='<div class="order-history-empty"><p style="font-size:14px;margin-bottom:4px">暂无历史订单</p><p style="font-size:12px;color:#999">快去下单吧</p></div>';return}el.innerHTML=S.orders.map(o=>'<div class="order-card"><div class="order-header"><span class="order-id">📄 '+o.id+'</span><span class="order-time">'+o.time+'</span><span class="order-status">已完成</span></div><div class="order-items">'+o.items.map(i=>i.name+'×'+i.qty).join('、')+'</div>'+(o.remark?'<div class="order-remark">💬 备注: '+o.remark+'</div>':'')+'<div class="order-total">'+fp(o.total)+'</div></div>').join('')}
function oom(){ro();document.getElementById('orderModal').classList.add('show')}
function com(){document.getElementById('orderModal').classList.remove('show')}
function cao(){if(!confirm('确定清空所有历史订单吗？此操作不可恢复。'))return;S.orders=[];sd();ro();showToast('所有订单已清空','info')}
function showToast(m,t){const c=document.getElementById('toastContainer'),o=document.createElement('div');o.className='toast '+(t||'info');o.textContent=m;c.appendChild(o);setTimeout(()=>o.remove(),2500)}
function init(){try{localStorage.removeItem('menu_data')}catch(e){}ld();const cc=document.getElementById('colorOptions');cc.innerHTML=CS.map(c=>'<div class="color-swatch" data-color="'+c+'" style="background:'+c+'"></div>').join('');cc.querySelectorAll('.color-swatch').forEach(el=>el.addEventListener('click',()=>hc(el.dataset.color)));hc(CS[0]);ra();const rmt=document.getElementById('remarkTags');if(rmt){['少吃辣','爱吃辣','不吃香菜','少油','少盐','不要葱','加急'].forEach(t=>{const el=document.createElement('span');el.className='cr-tag';el.textContent=t;el.addEventListener('click',()=>{const inp=document.getElementById('remarkInput');const txt=t;if(el.classList.contains('active')){el.classList.remove('active');const tags=inp.value.split('；').filter(x=>x.trim()&&x.trim()!==txt);inp.value=tags.join('；')}else{el.classList.add('active');const existing=inp.value.trim();inp.value=existing?(existing+'；'+txt):txt}inp.value=inp.value.trim()})})}}let st;document.getElementById('searchInput').addEventListener('input',()=>{clearTimeout(st);st=setTimeout(()=>{S.q=document.getElementById('searchInput').value;S.curCat=null;rs();rd()},250)})
document.getElementById('adminToggle').addEventListener('click',()=>{S.admin=!S.admin;const btn=document.getElementById('adminToggle');btn.textContent=S.admin?'✅ 完成管理':'⚙️ 管理菜品';btn.className=S.admin?'toolbar-btn toolbar-btn-success':'toolbar-btn toolbar-btn-primary';document.getElementById('adminBanner').classList.toggle('show',S.admin);document.getElementById('leftPanel').classList.toggle('admin-mode',S.admin);let ab=document.getElementById('addDishBtn');if(S.admin){if(!ab){ab=document.createElement('button');ab.id='addDishBtn';ab.className='toolbar-btn toolbar-btn-success';ab.innerHTML='➕ 添加菜品';ab.addEventListener('click',()=>odm(null));document.querySelector('.content-toolbar .ct-right').insertBefore(ab,document.querySelector('.content-toolbar .ct-right').firstChild)}}else if(ab)ab.remove();rd();rs()})
document.getElementById('cartBtn').addEventListener('click',oc);document.getElementById('cartOverlay').addEventListener('click',cc2);document.getElementById('cartCloseBtn').addEventListener('click',cc2);document.getElementById('checkoutBtn').addEventListener('click',so)
document.getElementById('dishEditClose').addEventListener('click',cdem);document.getElementById('dishEditCancel').addEventListener('click',cdem);document.getElementById('dishEditSave').addEventListener('click',sde);document.getElementById('dishEditModal').addEventListener('click',e=>{if(e.target===e.currentTarget)cdem()});document.getElementById('imageUploadArea').addEventListener('click',()=>{document.getElementById('imageFileInput').click()});document.getElementById('imageFileInput').addEventListener('change',async e=>{const f=e.target.files?.[0];if(!f||!f.type.startsWith('image/'))return;try{const raw=await rim(f),cmp=await cim(raw,400),pv=document.getElementById('uploadPreview');pv.src=cmp;pv.style.display='block';document.getElementById('uploadIcon').style.display='none';document.getElementById('uploadText').textContent='点击更换图片';document.getElementById('uploadClear').style.display='flex'}catch(e){showToast('图片读取失败','error')}});document.getElementById('uploadClear').addEventListener('click',e=>{e.stopPropagation();const pv=document.getElementById('uploadPreview');pv.style.display='none';pv.src='';document.getElementById('uploadIcon').style.display='block';document.getElementById('uploadText').innerHTML='点击 <strong>上传图片</strong>，支持 JPG / PNG';document.getElementById('uploadClear').style.display='none';document.getElementById('imageFileInput').value=''})
document.addEventListener('click',async e=>{const ov=e.target.closest('[data-action="upload"]');if(!ov||!S.admin)return;const row=ov.closest('.dish-row');if(!row)return;const did=row.dataset.id,inp=document.getElementById('imageFileInput');inp.value='';inp.click();inp.addEventListener('change',async function h(ev){inp.removeEventListener('change',h);const f=ev.target.files?.[0];if(!f||!f.type.startsWith('image/'))return;const d=fd(did);if(!d)return;try{const raw=await rim(f),cmp=await cim(raw,400);d.image=cmp;S.cart.forEach(i=>{if(i.dishId===d.id)i.image=cmp});sd();rd();rc();showToast('✅ '+d.name+' 图片已更新','success')}catch(e){showToast('图片上传失败','error')}})},true)
;['orderHistoryBtn','orderHistoryBtn2'].forEach(id=>{document.getElementById(id)?.addEventListener('click',oom)});document.getElementById('orderModalClose').addEventListener('click',com);document.getElementById('orderModalClose2Btn').addEventListener('click',com);document.getElementById('orderModal').addEventListener('click',e=>{if(e.target===e.currentTarget)com()});document.getElementById('clearOrdersBtn').addEventListener('click',cao)
document.getElementById('addCategoryBtn').addEventListener('click',()=>ocm(null));document.getElementById('catModalClose').addEventListener('click',ccm);document.getElementById('catCancelBtn').addEventListener('click',ccm);document.getElementById('catSaveBtn').addEventListener('click',scat);document.getElementById('catDeleteBtn').addEventListener('click',dcat);document.getElementById('categoryModal').addEventListener('click',e=>{if(e.target===e.currentTarget)ccm()})
document.getElementById('sidebarToggle').addEventListener('click',()=>{document.getElementById('leftPanel').classList.toggle('open')});document.querySelector('.right-content')?.addEventListener('click',()=>{document.getElementById('leftPanel').classList.remove('open')})
document.addEventListener('keydown',e=>{if(e.key==='Escape'){cc2();cdem();com();ccm()}})}
document.addEventListener('DOMContentLoaded',init);

}