"""create users table

Revision ID: 84045401e315
Revises: 
Create Date: 2026-09-13 21:56:54.348729+08:00

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# 迁移标识（Alembic 用它串起版本链，不要手改）
revision: str = '84045401e315'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """升级：把数据库结构改到本版本的样子。"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='用户 ID'),
    sa.Column('openid', sa.String(length=64), nullable=False, comment='微信 openid，同一小程序内唯一，登录时按它查找或创建用户'),
    sa.Column('unionid', sa.String(length=64), nullable=True, comment='微信 unionid，仅在绑定了微信开放平台账号时才有，用于跨应用识别同一用户'),
    sa.Column('nickname', sa.String(length=64), nullable=False, comment='昵称'),
    sa.Column('avatar_url', sa.String(length=512), nullable=True, comment='头像地址。注意：微信给的链接是临时地址会过期，不可长期依赖'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否可用，停用后无法登录'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_openid'), 'users', ['openid'], unique=True)
    op.create_index(op.f('ix_users_unionid'), 'users', ['unionid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """回滚：把本版本的改动撤销掉。"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_unionid'), table_name='users')
    op.drop_index(op.f('ix_users_openid'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
