"""create spaces and space_members tables

Revision ID: 677381f4d9ab
Revises: 84045401e315
Create Date: 2026-09-13 22:12:16.923416+08:00

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# 迁移标识（Alembic 用它串起版本链，不要手改）
revision: str = '677381f4d9ab'
down_revision: str | None = '84045401e315'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """升级：把数据库结构改到本版本的样子。"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spaces',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='家庭组 ID'),
    sa.Column('name', sa.String(length=32), nullable=False, comment='家庭组名称，允许重名（不同家庭叫同一个名字是正常的）'),
    sa.Column('owner_id', sa.BigInteger(), nullable=False, comment='创建者用户 ID，即该家庭组的管理员'),
    sa.Column('invite_code', sa.String(length=16), nullable=False, comment='邀请码，家人凭它加入家庭组'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spaces_invite_code'), 'spaces', ['invite_code'], unique=True)
    op.create_index(op.f('ix_spaces_owner_id'), 'spaces', ['owner_id'], unique=False)
    op.create_table('space_members',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('space_id', sa.BigInteger(), nullable=False, comment='家庭组 ID，删组时成员记录随之清理'),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='用户 ID'),
    sa.Column('role', sa.String(length=16), nullable=False, comment='成员角色：admin 管理员（创建者）/ member 普通成员'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['space_id'], ['spaces.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('space_id', 'user_id', name='uq_space_members_space_user')
    )
    op.create_index(op.f('ix_space_members_space_id'), 'space_members', ['space_id'], unique=False)
    op.create_index(op.f('ix_space_members_user_id'), 'space_members', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """回滚：把本版本的改动撤销掉。"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_space_members_user_id'), table_name='space_members')
    op.drop_index(op.f('ix_space_members_space_id'), table_name='space_members')
    op.drop_table('space_members')
    op.drop_index(op.f('ix_spaces_owner_id'), table_name='spaces')
    op.drop_index(op.f('ix_spaces_invite_code'), table_name='spaces')
    op.drop_table('spaces')
    # ### end Alembic commands ###
