"""create recipes table

Revision ID: 25bfc5bdf007
Revises: 677381f4d9ab
Create Date: 2026-09-13 23:16:52.807834+08:00

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# 迁移标识（Alembic 用它串起版本链，不要手改）
revision: str = '25bfc5bdf007'
down_revision: str | None = '677381f4d9ab'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """升级：把数据库结构改到本版本的样子。"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipes',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='菜谱 ID'),
    sa.Column('space_id', sa.BigInteger(), nullable=False, comment='所属家庭组。家庭组解散时，这个家的菜谱随之清理'),
    sa.Column('name', sa.String(length=64), nullable=False, comment='菜名，例如「番茄炒蛋」'),
    sa.Column('category', sa.String(length=16), nullable=False, comment='分类，取值必须是 RECIPE_CATEGORIES 之一'),
    sa.Column('description', sa.Text(), nullable=True, comment='做法或说明。第一版就存一整段文字，不做结构化食材'),
    sa.Column('image_url', sa.String(length=512), nullable=True, comment='菜品图片地址。第一版不做上传，先留字段，前端用 emoji 占位'),
    sa.Column('created_by', sa.BigInteger(), nullable=False, comment='添加者用户 ID，仅用于展示「谁加的」，不参与权限判断'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['space_id'], ['spaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recipes_created_by'), 'recipes', ['created_by'], unique=False)
    op.create_index('ix_recipes_space_category', 'recipes', ['space_id', 'category'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """回滚：把本版本的改动撤销掉。"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_recipes_space_category', table_name='recipes')
    op.drop_index(op.f('ix_recipes_created_by'), table_name='recipes')
    op.drop_table('recipes')
    # ### end Alembic commands ###
