<template>
  <view class="page-shell checkout-page">
    <view v-if="loading" class="state-card">正在确认菜品</view>
    <view v-else-if="items.length"><view class="page-head"><text class="page-title">确认订单</text><text class="page-copy">确认后将由店铺管理员处理</text></view><view class="order-card"><text class="section-title">菜品详情</text><view v-for="item in items" :key="item.cartKey" class="order-item"><view class="order-image" :style="{ background: item.color || '#fed7aa' }"><image v-if="item.imageUrl" :src="item.imageUrl" mode="aspectFill" /><text v-else>{{ item.emoji || '🍽️' }}</text></view><view class="order-copy"><text class="order-name">{{ item.name }}</text><text v-if="item.options?.length" class="order-options">{{ item.options.join('、') }}</text></view><view class="order-price"><text>¥{{ item.price }}</text><text class="order-quantity">{{ item.quantity }} 份</text></view></view></view><view class="remark-card"><text class="section-title">订单备注</text><textarea v-model="remark" class="remark-input" maxlength="80" placeholder="例如：少辣、不要香菜" /></view></view>
    <view v-else class="state-card">购物车为空，请先选择菜品</view>
    <view v-if="!loading && items.length" class="checkout-footer"><button class="back-button" :disabled="submitting" @click="backToMenu">继续点餐</button><button class="confirm-button" :loading="submitting" :disabled="submitting" @click="submitOrder">确认下单 ¥{{ total }}</button></view>
  </view>
</template>

<script setup>
import { computed, ref } from 'vue';
import { onShow } from '@dcloudio/uni-app';
import { useAuthStore } from '../../stores/auth';
import { useCartStore } from '../../stores/cart';
import { useShopStore } from '../../stores/shop';
import { createOrder } from '../../services/menu';
import { getGuestSessionId } from '../../utils/entry-code';
import { invalidateShopCache, readShopCache, refreshDishImageUrls } from '../../utils/shop-cache';
import { showError } from '../../utils/format';

const authStore = useAuthStore(); const cartStore = useCartStore(); const shopStore = useShopStore();
const loading = ref(true); const submitting = ref(false); const items = ref([]); const remark = ref('');
const total = computed(() => cartStore.total.toFixed(2));
function context() { return { shopId: shopStore.shopId, entryToken: shopStore.context?.entryToken || '', guestSessionId: getGuestSessionId() }; }
async function render() { loading.value = true; try { if (!cartStore.items.length) { items.value = []; return; } const cached = shopStore.hasShop ? readShopCache(shopStore.shopId, 'menu') : null; const dishes = await refreshDishImageUrls(cached?.data?.dishes || []); const images = new Map(dishes.map((dish) => [dish.id, dish.imageUrl || ''])); items.value = cartStore.items.map((item) => ({ ...item, imageUrl: images.get(item.id) || item.imageUrl || '' })); remark.value = String(uni.getStorageSync('uni_family_checkout_remark') || ''); } finally { loading.value = false; } }
async function submitOrder() { if (submitting.value || !cartStore.items.length) return; if (!authStore.isLoggedIn) { uni.setStorageSync('uni_family_checkout_remark', remark.value); uni.showModal({ title: '请先登录', content: '登录后才能提交订单，购物车会为你保留。', confirmText: '去登录', success: (result) => { if (result.confirm) uni.navigateTo({ url: `/pages/auth/index?returnTo=${encodeURIComponent('/pages/checkout/index')}` }); } }); return; } if (!shopStore.tableId) { uni.showModal({ title: '请先扫码确认桌位', content: '回到点菜页，点击“扫码”扫描本店桌码后再提交订单。', showCancel: false, success: () => uni.switchTab({ url: '/pages/menu/index' }) }); return; } submitting.value = true; try { const requestId = `order_${Date.now().toString(36)}_${Math.random().toString(36).slice(2, 12)}`; const result = await createOrder(context(), { items: cartStore.items.map((item) => ({ id: item.id, quantity: item.quantity, options: item.options || [] })), remark: remark.value.trim(), requireTable: true, tableId: shopStore.tableId, requestId }); if (!result?.ok || !result.order) { const names = Array.isArray(result?.dishNames) && result.dishNames.length ? result.dishNames.join('、') : '该菜品'; throw new Error(result?.code === 'OUT_OF_STOCK' ? `${names}库存不足，请调整数量后重试` : (result?.message || '提交订单失败')); } cartStore.clear(); uni.removeStorageSync('uni_family_checkout_remark'); invalidateShopCache(shopStore.shopId, 'menu'); uni.showToast({ title: '订单已提交', icon: 'success' }); setTimeout(() => uni.switchTab({ url: '/pages/orders/index' }), 450); } catch (error) { showError(error.message || '提交失败，请稍后重试'); } finally { submitting.value = false; } }
function backToMenu() { uni.navigateBack({ delta: 1 }); }
onShow(render);
</script>

<style scoped>
.checkout-page { min-height: 100vh; padding-bottom: calc(220rpx + env(safe-area-inset-bottom)); }.page-head { display: flex; flex-direction: column; gap: 8rpx; margin: 8rpx 4rpx 24rpx; }.page-title { color: #450a0a; font-size: 42rpx; font-weight: 700; }.page-copy { color: #78716c; font-size: 25rpx; }.state-card, .order-card, .remark-card { padding: 24rpx; border: 2rpx solid #fee2e2; border-radius: 18rpx; background: #fff; box-shadow: 0 8rpx 20rpx rgba(69, 10, 10, .05); }.state-card { margin-top: 140rpx; color: #78716c; font-size: 28rpx; text-align: center; }.section-title { display: block; margin-bottom: 16rpx; color: #450a0a; font-size: 30rpx; font-weight: 700; }.order-item { display: flex; align-items: center; gap: 16rpx; padding: 16rpx 0; border-top: 2rpx solid #fef2f2; }.order-item:first-of-type { border-top: 0; }.order-image { width: 100rpx; height: 100rpx; flex: 0 0 100rpx; display: flex; align-items: center; justify-content: center; overflow: hidden; border-radius: 14rpx; font-size: 40rpx; }.order-image image { width: 100%; height: 100%; }.order-copy { min-width: 0; flex: 1; display: flex; flex-direction: column; gap: 8rpx; }.order-name { overflow: hidden; color: #450a0a; font-size: 29rpx; font-weight: 700; text-overflow: ellipsis; white-space: nowrap; }.order-options { overflow: hidden; color: #78716c; font-size: 22rpx; text-overflow: ellipsis; white-space: nowrap; }.order-price { min-width: 88rpx; display: flex; flex-direction: column; align-items: flex-end; gap: 7rpx; color: #dc2626; font-size: 29rpx; font-weight: 700; }.order-quantity { color: #78716c; font-size: 22rpx; font-weight: 400; }.remark-card { margin-top: 18rpx; }.remark-input { width: 100%; height: 88rpx; padding: 14rpx; border: 2rpx solid #fecaca; border-radius: 12rpx; background: #fffafa; color: #450a0a; font-size: 26rpx; box-sizing: border-box; }.checkout-footer { position: fixed; right: 0; bottom: 0; left: 0; z-index: 10; display: flex; gap: 16rpx; padding: 18rpx 24rpx calc(18rpx + env(safe-area-inset-bottom)); border-top: 2rpx solid #fee2e2; background: #fff; }.back-button, .confirm-button { min-width: 0; height: 92rpx; margin: 0; padding: 0 16rpx; border-radius: 16rpx; font-size: 28rpx; font-weight: 700; line-height: 92rpx; }.back-button { flex: .9; border: 2rpx solid #dc2626; background: #fff; color: #b91c1c; }.confirm-button { flex: 1.55; background: #dc2626; color: #fff; }.back-button[disabled], .confirm-button[disabled] { opacity: .55; }
</style>
